services:
  api1:
    build:
      context: .
      dockerfile: api.Dockerfile
      args:
        - BUILD_DATE=$(date +%Y-%m-%d:%H:%M:%S)
    env_file:
    - ./api/.env
    ports:
    - "8081:3000"
    networks:
      - milestone-5-net
      
  api2:
    build:
      context: .
      dockerfile: api.Dockerfile
      args:
        - BUILD_DATE=$(date +%Y-%m-%d:%H:%M:%S)
    env_file:
    - ./api/.env
    ports:
    - "8082:3000"
    networks:
      - milestone-5-net
     
  nginx:
    build: 
      context: .
      dockerfile: nginx.Dockerfile
    ports:
      - 8080:8080
    depends_on:
      - api1
      - api2

networks:
  milestone-5-net:
    name: milestone-5-net
    external: true