services:
  api1:
    build:
      context: .
      dockerfile: api.Dockerfile
      args:
        - BUILD_DATE=$(date +%Y-%m-%d:%H:%M:%S)
    env_file:
    - ./api/.env
    ports:
    - "8081:8081"
    environment:
      - PORT=8081 # Default value, can be overridden
    networks:
      - milestone-5-net
      
  api2:
    build:
      context: .
      dockerfile: api.Dockerfile
      args:
        - BUILD_DATE=$(date +%Y-%m-%d:%H:%M:%S)
    env_file:
    - ./api/.env
    ports:
    - "8082:8082"
    environment:
      - PORT=8082 # Default value, can be overridden
    networks:
      - milestone-5-net
     
  nginx:
    build: 
      context: .
      dockerfile: nginx.Dockerfile
    ports:
      - 8080:8080
    depends_on:
      - api1
      - api2
    networks:
      - milestone-5-net

networks:
  milestone-5-net:
    name: milestone-5-net
    external: true