apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: vault-db-secrets
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  target:
    name: postgres-secret
  data:
  - secretKey: POSTGRES_USER
    remoteRef:
      key: kv/postgres-secrets # make sure this matches with what you create in the vault UI
      property: POSTGRES_USER # this is the secret you create under the path

  - secretKey: POSTGRES_PASSWORD
    remoteRef:
      key: kv/postgres-secrets # make sure this matches with what you create in the vault UI
      property: POSTGRES_PASSWORD # this is the secret you create under the path

  - secretKey: POSTGRES_DATABASE
    remoteRef:
      key: kv/postgres-secrets # make sure this matches with what you create in the vault UI
      property: POSTGRES_DATABASE # this is the secret you create under the path

  